### ISSUE TITLE
not available in Cuis 7?

### ISSUE THREAD

**Issue by mvolkmann** [Cuis-Smalltalk/Games#2]
When I enter `Feature require: 'Morphic-Games-Solitaire'` and a Workspace and "Do it", I get "Could not find code package file for [Morphic-Games-Solitaire]. Installation failed." Do we need to download this from this repo now?

**Comment by mvolkmann** [comment]
I have this working now. I just thought this package was included with Cuis. Here is what I did to install it and start a game:

- Clone this repository.
- Launch Cuis Smalltalk.
- Open a "File List" window.
- Locate and select the file `Morphic-Games-Solitaire.pck.st`.
- Click the "Install Package" button.
- Open a Workspace window.
- Enter something like `Freecell newGame` and "Do it".

**Comment by KenDickey** [comment]
On 2024-06-09 07:12, Mark Volkmann wrote:

> I have this working now. I just thought this package was included with 
> Cuis. Here is what I did to install it and start a game:
> 
> * Clone this repository.
> * Launch Cuis Smalltalk.
> * Open a "File List" window.
> * Locate and select the file Morphic-Games-Solitaire.pck.st.
> * Click the "Install Package" button.
> * Open a Workspace window.
> * Enter something like Freecell newGame and "Do it".

You created a new FreeCell Game, but did not add it to the 
display/desktop/World.

  FreeCell newGame openInHand. "or openInWorld"

Without typing..
   World Menu --> New Morph.. --> Layouts --> FreeCell

Also, you might open a CLI/Shell on Cuis-Smalltalk-Dev and invoke
   ./clonePackageRepos.sh

To get typical repositories.

As the repos and Cuis-Smalltalk are in sibling directories, `Feature 
require: <whatever>` should just work.

Good on ya,
-KenD

**Comment by KenDickey** [comment]
On 2024-06-09 07:12, Mark Volkmann wrote:

> * Enter something like Freecell newGame and "Do it".

Ah!  Many apologies!

I have not looked at the README.md for some years, apparently.

README.md instructions now updated.

Sorry for the confusion.

-KenD

**Comment by mvolkmann** [comment]
Actually, when I enter `FreeCell newGame` in a Workspace and "Do it", it does open. I do not need to call `openInWorld`.

**Comment by KenDickey** [comment]
On 2024-06-09 14:44, Mark Volkmann wrote:

> Actually, when I enter FreeCell newGame in a Workspace and "Do it", it 
> does open. I do not need to call openInWorld.

Yep.  I was looking at instance side..

Thanks!
-KenD
